print ("welcome to the love calculator ... ")
name1=input("whats your name ? ")
name2=input("whats their name ? ")
uninameA = name1 + name2
uniname = uninameA.lower()
countt=uniname.count("t")
countr=uniname.count("r")
countu=uniname.count("u")
counte=uniname.count("e")
rate1=str(countt+countr+countu+counte)
countl=uniname.count("l")
counto=uniname.count("o")
countv=uniname.count("v")
counte=uniname.count("e")
rate2=str(countl+counto+countv+counte)
final = int(rate1+rate2)
print(final)
